default:
  image: php:8.0.1-fpm-alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
phpunit:
  stage: test
  script:
    - sh ci/php-install.sh
    - composer install --prefer-dist -q --no-progress
    - ./vendor/bin/phpunit tests -v --coverage-text --colors=never --stderr
deploy_composer:
#  only:
#    - tags
  stage: deploy
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
stages:
  - test
  - deploy
